- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
         name: 66026011nextjs-container  # ใช้ตัวพิมพ์เล็กให้ตรงกับชื่อ image
         image: 66026011nextjs:latest    # เปลี่ยนให้เป็นตัวพิมพ์เล็ก
         ports:
           - "4832:80" #เลข port ตัวแรกคือเลข  port ที่รับมาจาก browser ตัวหลังคือ  port ของ docker (คงไว้ที่ 80 ถ้าเป็น nextjs project ก็ 3000)
         state: started
         restart: true
